# Generated by Django 5.0.7 on 2024-07-19 06:04

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BlogCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.CharField(max_length=255)),
                ("category_title", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("author", models.CharField(max_length=14)),
                ("thumbnail", models.ImageField(default="", upload_to="blog/images")),
                (
                    "timeStamp",
                    models.DateField(blank=True, default=datetime.datetime.now),
                ),
                ("add_to_top", models.BooleanField(default=False)),
                ("latest", models.BooleanField(default=False)),
                (
                    "Category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="blog.blogcategory",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Para",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.CharField(max_length=50)),
                ("sequence", models.IntegerField(default=1)),
                ("content", models.TextField(max_length=50000, null=True)),
                ("isDeleted", models.BooleanField(default=False)),
                (
                    "ad_field_image",
                    models.ImageField(default="", upload_to="blog/images"),
                ),
                ("ad_field_product_name", models.CharField(default="", max_length=10)),
                (
                    "ad_field_price",
                    models.CharField(blank=True, default="", max_length=10, null=True),
                ),
                (
                    "ad_field_model",
                    models.CharField(blank=True, default="", max_length=10, null=True),
                ),
                ("ad_field_link", models.URLField(blank=True, null=True)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="blog.post"
                    ),
                ),
            ],
        ),
    ]
